### PR TITLE
check if browser include setOrientation method for wdio5

### PR DESCRIPTION
**Pull request by SophieDePaula**
Seems that `setOrientation` does not exist in `wdio5`

### CODE REVIEW

**Comment by kyryloonufriiev** [comment]
What about wdio 6?

**Comment by SophieDePaula** [comment]
@kyryloonufriiev I don't see that other methods like `getSystemBars` and `getOrientation` were added to `v6.d.ts`. Did you handle it differently in `wido6`?

**Review by kyryloonufriiev — CHANGES_REQUESTED** [review]
Ah sorry. For some reason, I thought that wdio 6 also has some methods missed in the types.

Doesn't `setOrientation` accept an argument?

**Comment by SophieDePaula** [comment]
@kyryloonufriiev thanks for catching that, I fixed it.
Lmk, if there is anything else and if not I'll merge and release.

**Comment by SophieDePaula** [comment]
@kyryloonufriiev I changed it to just `string`, it does work with lowercase as well.

**Comment by kyryloonufriiev** [comment]
It works in terms of ts, but actually did you ever run this command with lowercase values? Because I see that you are passing lowercase values when I believe it should be uppercase.

**Comment by SophieDePaula** [comment]
@kyryloonufriiev yes, before I changed the logic to use the `width` in `landscape` mode the device flipping worked.

**Comment by kyryloonufriiev** [comment]
Ah. Then fine, however, it might not work for some older appium versions, but not important.

**Review by kyryloonufriiev — APPROVED** [review]

**Pull request merged**
