### PR TITLE
fixed obect sigparam x-> y

### PR DESCRIPTION
**Pull request by yonatanLehman**

### CODE REVIEW

**Comment by astappiev** [comment]
Created a new commit to master

**Comment by amitzur** [comment]
It seems like this PR is well out of scope of its title.
Why is this so?

**Comment by astappiev** [comment]
The branch was created from `develop`, and when I rebased `develop` on top of `master` the PR includes much more commits that expected. According to @danielputerman's flow we need to create branches only from master and develop should be rebased on top of master everytime something is pushed to master.

**Comment by astappiev** [comment]
Originally, the PR included only [one commit](https://github.com/applitools/eyes.sdk.javascript1/pull/101/commits/c0ff65d70f3978db2bc4d183548cccbb5be5541a), but I have cherry-picked it to master.

**Pull request closed without merging**
