### PR TITLE
Improved execute script logging

### PR DESCRIPTION
**Pull request by tourdedave**
Log what executeScript was trying to do when it threw an exception

### CODE REVIEW

**Comment by tourdedave** [comment]
I initially wanted to just `JSON.stringify(args)` but got a circular error when `args` included an element.

**Comment by kyryloonufriiev** [comment]
@tourdedave Maybe `JSON.stringify` is a good approach. We just need to have a reasonable `toJSON` and `toString` methods in `EyesElement` then we would benefit not only here but always when we want to log an element.

**Comment by amitzur** [comment]
@kyryloonufriiev @tourdedave what do you think we should have in our `EyesElement.toJSON` and `toString` in order to have this functionality?

**Comment by kyryloonufriiev** [comment]
I think `toJSON` should contain selector, parent context and framework element itself if it could be serialized. `toJSON` for context should contain parent context, frame element/reference, scroll root element and also there might be calculated metrics such as scroll position. Then `toSstring` could be just `${this.constructor.name} ${JSON.stringify(this, null, 2)}`

**Comment by tourdedave** [comment]
Works for me.

**Pull request closed without merging**
