### PR TITLE
Adding "shard" option to eyes-storybook

### PR DESCRIPTION
**Pull request by NoamGaash**
# Description:

This pull request adds a new feature to the eyes-storybook library by introducing the "shard" option. The "shard" option allows users to specify the current shard and total number of shards for visual testing in a distributed environment, enabling parallel execution and improved test performance.

# Changes Made:

- Added a new command-line option --shard to the eyes-storybook library, accepting the "current/total" format.
- Updated the documentation to include information about the new "shard" option and its usage.

# Motivation:

The motivation behind this feature is to enhance the scalability and efficiency of visual testing when running eyes-storybook in a distributed environment. By introducing the "shard" option, users can take advantage of parallel execution on multiple machines, reducing the overall test execution time and improving productivity.

# Benefits:

- Faster test execution: By dividing the test cases into multiple shards, visual testing can be performed in parallel, reducing the overall execution time.
- Improved performance: Distributing the tests across multiple shards enables better resource utilization and can significantly improve the performance of visual testing in distributed environments.
- Scalability: The "shard" option allows users to easily scale their visual testing infrastructure by adding more parallel shards as needed.

### CODE REVIEW

**Comment by NoamGaash** [comment]
I didn't manage to get the test suite to run,
If anyone is available for a ~10 minutes huddle, I'll appreciate your help with that :)

**Comment by amitzur** [comment]
@NoamGaash you can reach the same behavior by using the `include` option:
```
// applitools.config.js
module.exports = {
  include: ({index}) => {
    return index % totalShards === currShard - 1
  }
}
```

**Comment by NoamGaash** [comment]
@amitzur 
according the documentation:

> A predicate function, a string or a regular expression specifying which stories should be visually tested.<br/>Visual baselines will be created only for the components specified.<br/>The function receives an object with ```name```, ```kind```, ```storyTitle```  and ```parameters``` properties.<br/>For example (exclude all stories with a name that start with [SKIP]):<br/>```({name,  kind, storyTitle, parameters}) => !/^\[SKIP\]/.test(name)```<br/>For more information, see [per component configuration - include](#include)

it doesn't seem like there's such an option (seems like it's missing the `index` attribute), that's why we have used an uglier approach:

```ts
let shardIndex = 0;

module.exports = {
    ....
    include: () => {
        shardIndex++;
        return (shardIndex % SHARD_COUNT) === SHARD_INDEX - 1;
    }
};
```

I'll try using the `index` attribute. if it will work, I'll add it to the documentation.
I think that adding this type of usage as a recommended practice could also benefit some users.

**Comment by NoamGaash** [comment]
Thanks Amit!
The syntax you've suggested is much cleaner, and works perfectly on our branch.
I've made a better PR, that document the usage of sharding - #1734 
I'm closing this one, as the `shard` flag isn't needed.
Thank you! :pray: :medal_sports:

**Pull request closed without merging**
