### PR TITLE
Automatically link dev dependencies

### PR DESCRIPTION
**Pull request by amitzur**
This PR changes references to all dev dependencies inside the monorepo to be symlinks.
After merging this, need to run `yarn install --force` to get the symlink.
So from this point on, `yarn link` will only be needed for dependencies, and not dev dependencies.

We will still need to release versions of sdk-release-kit and sdk-shared because of dom-scripts, unless we want to agree on a relative path between these repos, and then we can specify a `link:` in the other repo as well.

### CODE REVIEW

**Review by tourdedave — APPROVED** [review]
I haven't used `link:` before, but LGTM

**Comment by amitzur** [comment]
@tourdedave because `file:` actually copies the files

**Comment by tourdedave** [comment]
Yeah, that's what I gathered. Much better.

**Comment by amitzur** [comment]
@tourdedave Why should TestCafe pose an issue? Because of Babel? If so, the `link:` is only for dev deps, why would it matter?

**Pull request merged**
