### PR TITLE
return test results from abortIfNotClosed

### PR DESCRIPTION
**Pull request by amitzur**
right now this method always returns undefined

### CODE REVIEW

**Comment by astappiev** [comment]
`abortIfNotClosed` is void method without a return value. The method is inherited Java SDK's implementation.
https://github.com/applitools/eyes.sdk.java3/blob/master/eyes.sdk.core/src/main/java/com/applitools/eyes/EyesBase.java#L894

**Comment by amitzur** [comment]
Thing is, before [this commit](https://github.com/applitools/eyes.sdk.javascript1/commit/57f4a7f47b85b3dfcb786dcae7711652c989056f#diff-dd9740fecc094ec0741c0ab0f5046bb5L936) it did return the test results from the server.
I think it's also the right behavior to return TestResults from this method because:
(a) there's data from the server to give to the user
(b) I need this info :-)

**Comment by astappiev** [comment]
Okay, will release update today.

**Comment by amitzur** [comment]
thank!
when can I expect it in npm?

**Comment by astappiev** [comment]
I'm working on another feature requested by @corevo which is also needed today. I planed to release them together in few hours. If you need it now, I can release it earlier.

**Comment by amitzur** [comment]
I don't need it now, next week is just fine. Thank you!

**Comment by astappiev** [comment]
Published in v. 4.4.0

**Pull request merged**
