### PR TITLE
feat: export deserialize dom snapshot

### PR DESCRIPTION
**Pull request by amitzur**

### CODE REVIEW

**Comment by kyrylodolynskyi** [comment]
Why do we need it?

**Comment by amitzur** [comment]
@kyrylodolynskyi for external consumers of takeDomSnapshots

**Comment by kyrylodolynskyi** [comment]
I don't understand. Why would they use it if we already made core to work without it.

**Comment by amitzur** [comment]
@kyrylodolynskyi oy, you're right. I was confused :facepalm:

**Pull request closed without merging**
