### PR TITLE
[storybook] Use eyes manager settings

### PR DESCRIPTION
**Pull request by kyrylodolynskyi**
I am applying the new `EyesManagerSettings` that should work with the latest core.
Also removing some redundancy in the `makeCore` and `makeManager`

### CODE REVIEW

**Comment by kyrylodolynskyi** [comment]
@SophieDePaula Please review

**Review by SophieDePaula — APPROVED** [review]
@kyrylodolynskyi makes sense to me as we create the `manager` here and use it to call `open` therefore we don't need to send `concurrency` to `makeCore`.
Also this matches the changes I see in master re how we send concurrency to `makeManager`.

**Comment by amitzur** [comment]
@SophieDePaula this LGTM but I would like to see that there is some failing test in Eyes-Storybook without this fix.

**Comment by amitzur** [comment]
@SophieDePaula @kyrylodolynskyi so was it the case that without this PR storybook tests were failing?

**Comment by kyrylodolynskyi** [comment]
> @SophieDePaula @kyrylodolynskyi so was it the case that without this PR storybook tests were failing?

The concurrency test was failing, because concurrency wasn't passed.

**Pull request merged**
