### PR TITLE
[core] Cleanup dead core

### PR DESCRIPTION
**Pull request by kyryloonufriiev**
Attempt to reduce confusion by removing code replaced by the `eyes-api` package, mostly enums and some functional classes like triggers that we never actually use.

As a next step, I see removing all the data classes and consolidating basic utils under the `utils` package.

### CODE REVIEW

**Review by tourdedave — CHANGES_REQUESTED** [review]
Looks good to me, but I'm not too familiar with all of the dead code. So I'm relying more on the tests to make sure there's nothing missed There are a few failures:

```
 1) core e2e
       produces correct snapshot for pages with data url as IMAGE in iframes:
     WebDriverError: unknown error: net::ERR_CONNECTION_REFUSED
  (Session info: headless chrome=99.0.4844.84)
      at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:522:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:548:13)
      at Executor.execute (node_modules/selenium-webdriver/lib/http.js:474:28)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Object.execute (node_modules/selenium-webdriver/lib/webdriver.js:735:17)
      at async Context.<anonymous> (test/e2e/dom-snapshot.e2e.spec.js:17:5)

  2) core e2e
       produces correct snapshot for pages with data url as HTML in iframes:
     WebDriverError: unknown error: net::ERR_CONNECTION_REFUSED
  (Session info: headless chrome=99.0.4844.84)
      at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:522:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:548:13)
      at Executor.execute (node_modules/selenium-webdriver/lib/http.js:474:28)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Object.execute (node_modules/selenium-webdriver/lib/webdriver.js:735:17)
      at async Context.<anonymous> (test/e2e/dom-snapshot.e2e.spec.js:31:5)

  3) MatchWindowData
       "before all" hook for "constructor without arguments":
     TypeError: Cannot read properties of undefined (reading 'MouseAction')
      at Context.<anonymous> (test/unit/match/MatchWindowData.spec.js:18:46)
      at processImmediate (node:internal/timers:464:21)

  4) Uncaught error outside test suite:
     Uncaught Cannot find module '../../../lib/close/BatchClose'
Require stack:
- /Users/me/Documents/_dev/applitools/eyes.sdk.javascript1/packages/eyes-sdk-core/test/unit/close/BatchClose.spec.js
- /Users/me/Documents/_dev/applitools/eyes.sdk.javascript1/packages/eyes-sdk-core/node_modules/mocha/lib/esm-utils.js
- /Users/me/Documents/_dev/applitools/eyes.sdk.javascript1/packages/eyes-sdk-core/node_modules/mocha/lib/mocha.js
- /Users/me/Documents/_dev/applitools/eyes.sdk.javascript1/packages/eyes-sdk-core/node_modules/mocha/lib/nodejs/worker.js
  Error: Cannot find module '../../../lib/close/BatchClose'
  Require stack:
  - /Users/me/Documents/_dev/applitools/eyes.sdk.javascript1/packages/eyes-sdk-core/test/unit/close/BatchClose.spec.js
      at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
      at Function.Module._load (node:internal/modules/cjs/loader:778:27)
      at Module.require (node:internal/modules/cjs/loader:1005:19)
      at require (node:internal/modules/cjs/helpers:102:18)
      at Object.<anonymous> (test/unit/close/BatchClose.spec.js:1:24)
      at Module._compile (node:internal/modules/cjs/loader:1101:14)
      at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
      at Module.load (node:internal/modules/cjs/loader:981:32)
      at Function.Module._load (node:internal/modules/cjs/loader:822:12)
      at Module.require (node:internal/modules/cjs/loader:1005:19)
```

1 & 2 also fail on master for me, so might just be my local environment. But 3 and 4 look relevant.

**Comment by kyryloonufriiev** [comment]
@tourdedave agree. I forget to clean up those tests for batches.  About 1 and 2 it doesn't work because of macos, we use localhost in a docker container there.

**Comment by tourdedave** [comment]
Right, the localhost/host.docker.internal thing. Then shouldn't the test use `127.0.0.1` instead of `localhost` to make it work on all platforms?

**Review by amitzur — CHANGES_REQUESTED** [review]
1. Eyes-Images, Cypress, and Storybook both use `TestResultsStatus` from core (or via vgc).
2. vgc uses `AccessibilityRegionType` and `BrowserType` from core

I hope that's all the missing parts. It's hard to come up with. I would recommend to run all tests in all SDK's to be sure.

**Comment by amitzur** [comment]
> Right, the localhost/host.docker.internal thing. Then shouldn't the test use `127.0.0.1` instead of `localhost` to make it work on all platforms?

I see we replace `localhost` with `host.docker.internal` in `adjustUrlToDocker`. So I think it should be fine to use `localhost`. But maybe we need to add `adjustUrlToDocker` to `core-e2e-utils.js`? I never ran these tests with Mac to see it. Can you try @tourdedave ?

**Comment by kyryloonufriiev** [comment]
@amitzur @tourdedave I've fixed all of the tests and removed dependencies from other packages. Also made core more browser friendly.

**Pull request merged**
