### PR TITLE
docs: startStorybookServerTimeout

### PR DESCRIPTION
**Pull request by NoamGaash**

### CODE REVIEW

**Review by kyrylodolynskyi — APPROVED** [review]
Looks good to me. @amitzur @benbabayoff8 do we want this property to be documented in the first place?

**Comment by amitzur** [comment]
@NoamGaash sorry for the delay in this. Why is it important to expose this in the cli in addition to the `applitools.config.js` file (where it's already supported?)
I think the better point here is to document it in the documentation.

**Comment by NoamGaash** [comment]
@amitzur what do you mean by exposing?
just to be clear, this PR is documentation-only.
I didn't find this flag documented, and it was crucial to our pipeline

**Comment by NoamGaash** [comment]
@kyrylodolynskyi

**Comment by amitzur** [comment]
@NoamGaash sorry, it was my confusion. I thought this PR was about exposing it in the CLI in addition to the config file. I'm merging this.

**Comment by NoamGaash** [comment]
@amitzur @kyrylodolynskyi cool! thank you

**Pull request merged**
