### PR TITLE
Remove legacy packages

### PR DESCRIPTION
**Pull request by amitzur**
Removed folders:
1. eyes-common-legacy
2. eyes-sdk-core-legacy
3. eyes-cypress-legacy
4. eyes-images-legacy
5. eyes-leanft
6. eyes-selenium-3
7. eyes-webdriverio-4-service

Once merged, I'll tag the one-commit-back on `master` as `legacy-packages`

### CODE REVIEW

**Review by tourdedave — APPROVED** [review]
🤩

**Comment by kyryloonufriiev** [comment]
Love it 😍

**Comment by kyryloonufriiev** [comment]
What about renaming `eyes-webdriverio-5` to `eyes-webdriverio`, since this name doesn't make sense for years?

**Comment by amitzur** [comment]
> What about renaming `eyes-webdriverio-5` to `eyes-webdriverio`, since this name doesn't make sense for years?

Good idea, I'll do it in another PR

**Pull request merged**
