### PR TITLE
Chromedriver multi-version support

### PR DESCRIPTION
**Pull request by tourdedave**
With yarn we can install multiple versions of the same package -- each with their own alias that can be required on its own ([link](https://classic.yarnpkg.com/en/docs/cli/add/#toc-yarn-add-alias)).

This is an example of doing it for `chromedriver`, wired up for use in the WDIO5 SDK.

### CODE REVIEW

**Comment by kyryloonufriiev** [comment]
I thought we want to do that with docker containers.

**Comment by tourdedave** [comment]
Ideally, yes. This is an incremental improvement that will help fix the immediate issue of differences between each of our machines (e.g., Linux tends to lag behind in the Chrome version that's available). There are also still a fair number of tests that rely on spinning up chromedriver locally across all SDKs.

**Comment by danielschwartz85** [comment]
Looks good

**Comment by amitzur** [comment]
@tourdedave can we close this in favor of working on docker containers?

**Comment by tourdedave** [comment]
Depends on how long until we implement containers.

**Comment by amitzur** [comment]
Next week max

**Comment by tourdedave** [comment]
Works for me. We can close this.

**Comment by amitzur** [comment]
Cool. I think the API of `CHROME_MAJOR_VERSION` still has merit. I just imagine it spinning the right docker container.
I'm aware that it's a performance overhead though and this PR might be a better solution for local chrome.
Let's not close this yet, and revisit when work on docker is done.

**Comment by tourdedave** [comment]
Closing this since I don't think we'll need it.

**Pull request closed without merging**
