### PR TITLE
Add support for edgechromium-1

### PR DESCRIPTION
**Pull request by amirhalatzi**
VG now support edgechromium-1, so why not support this version too?

### CODE REVIEW

**Comment by amitzur** [comment]
I'll talk about this with Gal today

**Comment by amirhalatzi** [comment]
Wasn't the whole 'feature flag' thing was to avoid these convos?

**Comment by amitzur** [comment]
Yes, we can merge it no problem. But I interpreted your comment-question as a nice-to-have, and I'm talking with Gal in 4 hours, and maybe this feature is going to be production-ready by next week, so I thought this can wait.

**Comment by amitzur** [comment]
merged in #163

**Pull request closed without merging**
