### PR TITLE
chore(java/*): add support for log event command

### PR DESCRIPTION
**Pull request by IdosApplitools**
* Added support for `Core.logEvent` command
* Fixed an issue with incorrect version in agentId

The SDK will send `Core.logEvent` right before `eyes.open` with the following settings in order to log the runtime Java version:

```
"settings": {
        "serverUrl": "https://eyesapi.applitools.com",
        "apiKey": "*****************",
        "level": "Notice",
        "type": "JAVA_VERSION",
        "javaVersion": "11.0.12"
    }
```

### CODE REVIEW

**Comment by kyrylodolynskyi** [comment]
@IdosApplitools FYI the shape you have added in the description is wrong. Take a look at this type - [LogEventSettings](https://github.com/applitools/eyes.sdk.javascript1/blob/d60cf1616741a96b152a1548760bb98116e5c3f9/js/packages/core-base/src/types.ts#L217-L221).
In your case, it is going to look like
```json
{
  "serverUrl": "https://eyesapi.applitools.com",
  "apiKey": "*****************",
  "level": "Notice",
  "event": {
    "type": "JAVA_VERSION",
    "javaVersion": "11.0.12"
  }
}
```

**Comment by IdosApplitools** [comment]
Updated structure to:

```
"settings": {
        "serverUrl": "https://eyesapi.applitools.com",
        "apiKey": "************",
        "level": "Notice",
        "event": {
            "type": "JAVA_VERSION",
            "javaVersion": "11.0.12"
        }
    }
```

**Comment by amitzur** [comment]
@IdosApplitools @kyrylodolynskyi we currently send `runnerStarted` event from core with this type of information, but Node.js related. I think for the sake of consistency, and in order to avoid different behavior in different SDK's, we should have an API of passing some information in `makeCore` which will be included in the `runnerStarted` event.

**Comment by IdosApplitools** [comment]
Closing this PR due to https://github.com/applitools/eyes.sdk.javascript1/pull/1842

**Pull request closed without merging**
