### PR TITLE
Add package eyes-sdk-utils

### PR DESCRIPTION
**Pull request by amitzur**
This PR serves the purpose of supporting the visual-grid-client as an isomorphic package that can also run in the browser.
The `config.js` file is a utility that is used by `eyes.cypress` and `eyes.storybook` SDK's, and was imported from the visual-grid-client.
Going forward, there are more utilities I'd like to introduce into this `eyes-sdk-utils` package, for example https://github.com/applitools/eyes.cypress/blob/master/src/plugin/waitForBatch.js and its dependent scripts, which provide a utility for waiting the visual-grid-client to end and output the results in an appealing and consistent way.
Finally, this is a step towards the end goal which is to merge `eyes.cypress` and `eyes.storybook` into this monorepo.

Let me know what you thinks @astappiev @danielputerman @corevo and the next step after this PR would be to release v1.0.0 of this package

### CODE REVIEW

**Comment by amitzur** [comment]
where are we with this PR?

**Comment by amitzur** [comment]
is this published in npm?

**Comment by amitzur** [comment]
where are the changes you are referring to?

**Comment by astappiev** [comment]
In the development branch.

On Jan 6, 2019 1:32 PM, "Amit Zur" <notifications@github.com> wrote:

where are the changes you are referring to?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/applitools/eyes.sdk.javascript1/pull/59#issuecomment-451734521>,
or mute the thread

**Comment by amitzur** [comment]
folks, we need to move this forward.
are there any roadblocks? @danielputerman @astappiev

**Comment by astappiev** [comment]
Hi Amit,

Let's talk/chat tomorrow about visual-grid-client and then we can go on.

Do you available for a call tomorrow?

**Pull request merged**
