### PR TITLE
chore(visual-grid-client): support multiple bcs hooks

### PR DESCRIPTION
**Pull request by tool3**
[trello](https://trello.com/c/JYn99gKJ)
[trello](https://trello.com/c/GMWV2GAw)

this PR introduces the ability to run a before capture screenshot hook per browser.

previously, you could only specify a single bcs hook for all browsers in the customer's configuration.

### API
before:
```javascript
{
  scriptHooks: {
    beforeCaptureScreenshot: 'script that will run before each browser render'
  }
}
```
after:
```javascript
{
  scriptHooks: {
    beforeCaptureScreenshot: { 
      chrome: 'script that will run before rendering on chrome',
      firefox: 'script that will run before rendering on firefox',
      default: 'script that will run before rendering all other browsers'
    } 
  }
}
```

### CODE REVIEW

**Comment by kyryloonufriiev** [comment]
What about API for core-based SDKs?

**Comment by tool3** [comment]
> What about API for core-based SDKs?

we will wait for `eyes-api` package and implement this logic there. 
the other option is to implement it now in core, but since this is not an urgent feature, we can wait.

**Comment by amitzur** [comment]
@tool3 @kyryloonufriiev there were also different implementation details that I spoke with Tal regarding the API that vgc exposes. We can talk about it f2f2

**Comment by kyryloonufriiev** [comment]
Closing this PR, and moving discussion on the API to the [Trello](https://trello.com/c/dhdxaODs/40-support-multiple-bcs-hooks)

**Pull request closed without merging**
