### PR TITLE
Support edgechromium-2

### PR DESCRIPTION
**Pull request by amirhalatzi**
We now support edgechromium-2 in the UFG

### CODE REVIEW

**Comment by danielschwartz85** [comment]
@amirhalatzi I'm getting `Unsupported browser or browser version 'edgechromium-2'`, is it suppose to be supported soon ?

**Comment by amirhalatzi** [comment]
Yes. I was sure it was already enabled in the UFG. It will be EoD

**Comment by amirhalatzi** [comment]
@danielschwartz85 give it a whirl now

**Comment by danielschwartz85** [comment]
> @danielschwartz85 give it a whirl now

works :+1:

**Pull request merged**
